name: AI Enrichment (labels + embeddings)

on:
  schedule:
    - cron: "0 10 * * *"   # daily at 10:00 UTC
  workflow_dispatch:

jobs:
  enrich:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "openai>=1.0.0" "supabase>=2.4.0" "python-dotenv>=1.0.0"

      - name: Verify OPENAI_API_KEY present
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python - <<'PY'
import os, sys
val = os.getenv("OPENAI_API_KEY")
print("OPENAI_API_KEY set? ", bool(val))
print("Length: ", len(val) if val else 0)
sys.exit(0 if val else 1)
PY

      - name: Run enrichment
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          AI_BATCH: "60"
          AI_MAX_CHARS: "8000"
          EMBED_MODEL: "text-embedding-3-small"
        run: |
          OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" python scripts/enrich_ai.py
