name: Nightly Ingest (Gorgias → Supabase)

on:
  # schedule:
  #   - cron: "0 9 * * *"  # runs daily at 09:00 UTC
  workflow_dispatch: {}   # allow manual runs from the Actions tab

concurrency:
  group: ingest-gorgias
  cancel-in-progress: false

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ingest script
        env:
          # --- Required secrets ---
          GORGIAS_EMAIL: ${{ secrets.GORGIAS_EMAIL }}
          GORGIAS_API_KEY: ${{ secrets.GORGIAS_API_KEY }}
          GORGIAS_SUBDOMAIN: ${{ secrets.GORGIAS_SUBDOMAIN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

          # --- Tunable ENV VARS ---
          # Ticket paging window (rolling refresh)
          MAX_PAGES: "5"             # how many ticket pages per run
          PAGE_LIMIT: "100"          # tickets per page

          # Message fetching (to avoid 429s)
          MAX_MESSAGE_FETCH_PER_RUN: "100"  # cap how many tickets get messages each run
          MSG_LIMIT: "50"                   # messages per ticket API call
          MSG_SLEEP: "0.20"                 # seconds between message calls (helps avoid 429s)
        run: |
          python scripts/gorgias_ingest.py
