name: Nightly Ingest (Gorgias → Supabase)

on:
  schedule:
    - cron: "0 9 * * *"  # runs daily at 09:00 UTC
  workflow_dispatch: {}   # allow manual runs from the Actions tab

concurrency:
  group: ingest-gorgias
  cancel-in-progress: false

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ingest script
        env:
          GORGIAS_EMAIL: ${{ secrets.GORGIAS_EMAIL }}
          GORGIAS_API_KEY: ${{ secrets.GORGIAS_API_KEY }}
          GORGIAS_SUBDOMAIN: ${{ secrets.GORGIAS_SUBDOMAIN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          python scripts/gorgias_ingest.py
